[project]
name = "drawit"
version = "0.2.0"
description = "Draw a binary tree"
readme = "README.md"
authors = [
    { name = "Hai Vu", email = "haivu2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "drawtree>=0.1.2",
]

[project.scripts]
drawit = "drawit:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.15.0",
    "ruff>=0.15.20",
]
