[project]
name = "drawit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hai Vu", email = "haivu2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "graphviz>=0.21",
]

[project.scripts]
drawit = "drawit:main"
drawit-bintree = "drawit.bintree:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
