[project]
name = "drawit"
version = "0.6.0"
description = "Draw a binary tree"
readme = "README.md"
authors = [{ name = "Hai Vu", email = "haivu2004@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "matplotlib>=3.11.0",
    "networkx>=3.6.1",
]

[project.scripts]
drawtree = "drawit.draw_tree_networkx:main"
d3 = "drawit.draw_tree_networkx:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["ipython>=9.15.0", "pytest>=9.1.1", "ruff>=0.15.20", "ty>=0.0.55"]
